### ISSUE TITLE
Add discord canary and PtB support

### ISSUE THREAD

**Issue by Czekoloczek** [Reavert/VisualStudioDiscordRPC#53]
Right now you need to have Discord Stable version opened for the extension to work

**Comment by Reavert** [comment]
I just tested the extension using Discord PTB, and it works...

**Comment by Czekoloczek** [comment]
then i might have an skill issue

**Comment by Czekoloczek** [comment]
can you test it on Canary? (i was on canary and it didn't work (or I have a skill issue))

**Comment by Reavert** [comment]
Just tested on Canary and it also works.
![image](https://github.com/Reavert/VisualStudioDiscordRPC/assets/55898777/63d21349-1bdc-4a0e-843f-ad43b8f04db1)
Maybe the problem is something else? Try to open your Discord or Visual Studio with administartor rights. Previously, there were problems that were solved in this way.
