### ISSUE TITLE
Profile "Playing" is not showing multiple instances anymore

### ISSUE THREAD

**Issue by miken2c** [Reavert/VisualStudioDiscordRPC#55]
When i had multiple instances of Visual Studio open it used to show each file under my profile activities, but now it only shows one.

Does discord modified how it works?

**Comment by Reavert** [comment]
Most likely, yes. Discord shows only one instance of the application.
I checked on other applications, and I also can only one instance.

**Comment by miken2c** [comment]
@Reavert i tested with multiple instances of VSCode and it does show all of the, i have 4 instances of Visual Studio 2022 (preview) open but it shows only one.
![image](https://github.com/user-attachments/assets/ff1bb2ca-bb7e-4d64-b537-bb49e50a8834)

**Comment by Reavert** [comment]
You see preview of two different extensions that you have installed. This is not "multiple instances" of the same extension.
The first extension is from the Crawl developer, the second is from leonardssh. 
This extensions have different names, icons, and most importantly, the Discord application ID, which they use to interact with Discord.
That's why you see them.
